[project]
authors = ["Chris Fonnesbeck <fonnesbeck@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "bayes_course"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
hvplot = "*"
ipython = "*"
ipywidgets = "*"
jupyter_client = "*"
jupyter_core = "*"
jupyterlab = "*"
pandas = "*"
patsy = "*"
pip = "*"
polars = "*"
pyarrow = "*"
pymc = "*"
pydot = "*"
python-graphviz = "*"
scipy = "*"
seaborn = "*"
setuptools = "*"
watermark = "*"
preliz = ">=0.12.0,<0.13"
altair = ">=5.5.0,<6"
nutpie = ">=0.13.2,<0.14"
numba = ">=0.60.0,<0.61"

[pypi-dependencies]
jax = { version = "*", extras = ["cpu"] }
numpyro = { version = "*", extras = ["cpu"] }
